name:                caching-vault
version:             0.1.0.0
github:              "agrafix/caching-vault"
license:             BSD3
author:              "Alexander Thiemann"
maintainer:          "Alexander Thiemann <mail@thiemann.at>"
copyright:           "2021 Alexander Thiemann"

extra-source-files:
  - README.md

synopsis:            A vault-style cache implementation
category:            Data

description:         Allows a central cache for arbitrary values with expiry dates

dependencies:
  - base >= 4.7 && < 5
  - time
  - stm
  - stm-containers
  - text

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates

default-extensions:
  - OverloadedStrings
  - DataKinds
  - TypeOperators
  - TypeFamilies
  - GADTs
  - FlexibleInstances
  - FlexibleContexts
  - MultiParamTypeClasses
  - StrictData
  - ScopedTypeVariables
  - DeriveGeneric
  - DeriveFunctor

library:
  source-dirs: src

tests:
  caching-vault-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - caching-vault
      - hspec
      - timespan
